# Did you know all JSON is valid YAML?
{
  'name': 'CI',
  'on':
    {
      'push': { 'branches': ['main'] },
      'pull_request': { 'branches': ['main'] }
    },
  'jobs':
    {
      'build':
        {
          'runs-on': 'ubuntu-latest',
          'steps':
            [
              {
                'uses': 'actions/checkout@v2',
                'name': 'Checkout'
              },
              {
                'uses': 'actions/setup-node@v1',
                'name': 'Use Node.js ${{ matrix.node-version }}',
                'with': { 'node-version': '15.x' }
              },
              {
                'name': 'Style check',
                'uses': 'actionsx/prettier@v2',
                'with': { 'args': '--check .' }
              },
              { 'run': 'npm ci', 'name': 'Install' },
              { 'run': 'npm run build', 'name': 'Build' },
              { 'run': 'npm run test --if-present', 'name': 'Test' }
            ]
        }
    }
}
